name: Release

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'SpotifyWPF/SpotifyWPF.csproj'
      - 'SpotifyWPF/app.manifest'
      - 'SpotifyWPF.MSIX/Package.appxmanifest'
      - '.github/workflows/release.yml'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and create GitHub Release
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

  # Removed VS component setup to avoid unknown action errors. We'll fallback to manual MakeAppx if Desktop Bridge isn't present.

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Extract version
        id: version
        run: |
          $csproj = Get-Content './SpotifyWPF/SpotifyWPF.csproj'
          $m = Select-String -InputObject $csproj -Pattern '<Version>([^<]+)</Version>' -AllMatches
          if (-not $m.Matches.Success) { Write-Error 'Version element not found in csproj.' }
          $version = $m.Matches[0].Groups[1].Value.Trim()
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "TAG=v$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "tag=v$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          Write-Host "Detected version: $version"
        shell: pwsh

      - name: Restore
        run: dotnet restore .\SpotifyWPF.sln
        shell: pwsh

      - name: Build (Release)
        run: dotnet build .\SpotifyWPF\SpotifyWPF.csproj -c Release --no-restore
        shell: pwsh

      - name: Create ZIP of Release binaries
        run: |
          $zipName = "SpotifyWPF-$env:VERSION.zip"
          $src = "${{ github.workspace }}\SpotifyWPF\bin\Release\net8.0-windows\*"
          $dst = "${{ github.workspace }}\$zipName"
          If (Test-Path $dst) { Remove-Item $dst -Force }
          Compress-Archive -Path $src -DestinationPath $dst -Force
          Write-Host "Created archive: $dst"
        shell: pwsh

      - name: Build portable single-file EXE (win-x64)
        run: |
          $out = "${{ github.workspace }}\artifacts\portable\win-x64"
          dotnet publish .\SpotifyWPF\SpotifyWPF.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:SelfContained=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -p:DebugSymbols=false -o $out
          $exe = Join-Path $out 'SpotifyWPF.exe'
          $dest = "${{ github.workspace }}\SpotifyWPF-$env:VERSION-portable-win-x64.exe"
          Copy-Item $exe $dest -Force
          Write-Host "Portable EXE: $dest"
        shell: pwsh

      - name: Build MSIX (unsigned) via WAP project
        id: msix
        run: |
          $out = "${{ github.workspace }}\artifacts\msix"
          New-Item -ItemType Directory -Force -Path $out | Out-Null
          msbuild .\SpotifyWPF.MSIX\SpotifyWPF.MSIX.wapproj /t:Restore,Rebuild /p:Configuration=Release `
            /p:UapAppxPackageBuildMode=SideLoadOnly /p:AppxBundle=Never /p:AppxPackageSigningEnabled=false /p:AppxPackageDir="$out"
          $msix = Get-ChildItem $out -Filter *.msix -Recurse | Select-Object -First 1
          if (-not $msix) { Write-Error 'MSIX package not found.' }
          $dest = "${{ github.workspace }}\SpotifyWPF-$env:VERSION.msix"
          Copy-Item $msix.FullName $dest -Force
          "MSIX_PATH=$dest" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          Write-Host "MSIX: $dest"
        shell: pwsh

      - name: Upload ZIP and portable EXE
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            ${{ github.workspace }}\SpotifyWPF-${{ steps.version.outputs.version }}.zip
            ${{ github.workspace }}\SpotifyWPF-${{ steps.version.outputs.version }}-portable-win-x64.exe

      - name: Upload MSIX artifact
        if: ${{ steps.msix.outputs.MSIX_PATH != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: release-msix
          path: ${{ steps.msix.outputs.MSIX_PATH }}

      - name: Create GitHub Release (zip + exe)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          target_commitish: ${{ github.sha }}
          name: SpotifyWPF v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            SpotifyWPF-${{ steps.version.outputs.version }}.zip
            SpotifyWPF-${{ steps.version.outputs.version }}-portable-win-x64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach MSIX to Release (if present)
        if: ${{ steps.msix.outputs.MSIX_PATH != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          files: ${{ steps.msix.outputs.MSIX_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
